# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tyto/runtime/v1/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tyto/runtime/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctyto/runtime/v1/common.proto\x12\x0ftyto.runtime.v1\"G\n\x0fTemplateBinding\x12\x13\n\x0btemplate_id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0e\n\x06\x64igest\x18\x03 \x01(\t\"\xe4\x01\n\rNetworkPolicy\x12\x31\n\x04mode\x18\x01 \x01(\x0e\x32#.tyto.runtime.v1.NetworkPolicy.Mode\x12+\n\x05\x61llow\x18\x02 \x03(\x0b\x32\x1c.tyto.runtime.v1.NetworkRule\"s\n\x04Mode\x12\x1c\n\x18NETWORK_MODE_UNSPECIFIED\x10\x00\x12\x19\n\x15NETWORK_MODE_STANDARD\x10\x01\x12\x19\n\x15NETWORK_MODE_DENY_ALL\x10\x02\x12\x17\n\x13NETWORK_MODE_CUSTOM\x10\x03\"M\n\x0bNetworkRule\x12\x0e\n\x04\x63idr\x18\x01 \x01(\tH\x00\x12\x10\n\x06\x64omain\x18\x02 \x01(\tH\x00\x12\r\n\x05ports\x18\x03 \x03(\rB\r\n\x0b\x64\x65stinationB<Z:github.com/bonyai/compute/gen/go/tyto/runtime/v1;runtimev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tyto._proto.tyto.runtime.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/bonyai/compute/gen/go/tyto/runtime/v1;runtimev1'
  _globals['_TEMPLATEBINDING']._serialized_start=49
  _globals['_TEMPLATEBINDING']._serialized_end=120
  _globals['_NETWORKPOLICY']._serialized_start=123
  _globals['_NETWORKPOLICY']._serialized_end=351
  _globals['_NETWORKPOLICY_MODE']._serialized_start=236
  _globals['_NETWORKPOLICY_MODE']._serialized_end=351
  _globals['_NETWORKRULE']._serialized_start=353
  _globals['_NETWORKRULE']._serialized_end=430
# @@protoc_insertion_point(module_scope)
