# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import guest_pb2 as tyto_dot_runtime_dot_v1_dot_guest__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tyto/runtime/v1/guest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GuestServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/Health',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.HealthRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.PostRestore = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/PostRestore',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.PostRestoreRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.PostRestoreResponse.FromString,
                _registered_method=True)
        self.PrepareSuspend = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/PrepareSuspend',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.PrepareSuspendRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.PrepareSuspendResponse.FromString,
                _registered_method=True)
        self.AbortSuspend = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/AbortSuspend',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.AbortSuspendRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.AbortSuspendResponse.FromString,
                _registered_method=True)
        self.PrepareResume = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/PrepareResume',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.PrepareResumeRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.PrepareResumeResponse.FromString,
                _registered_method=True)
        self.FreezeFilesystem = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/FreezeFilesystem',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.FreezeFilesystemRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.FreezeFilesystemResponse.FromString,
                _registered_method=True)
        self.ThawFilesystem = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/ThawFilesystem',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ThawFilesystemRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ThawFilesystemResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_stream(
                '/tyto.runtime.v1.GuestService/ReadFile',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.stream_unary(
                '/tyto.runtime.v1.GuestService/WriteFile',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.ListDirectory = channel.unary_stream(
                '/tyto.runtime.v1.GuestService/ListDirectory',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ListDirectoryRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ListDirectoryResponse.FromString,
                _registered_method=True)
        self.StatFile = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/StatFile',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.StatFileRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.StatFileResponse.FromString,
                _registered_method=True)
        self.MakeDirectory = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/MakeDirectory',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.MakeDirectoryRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.MakeDirectoryResponse.FromString,
                _registered_method=True)
        self.RemoveFile = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/RemoveFile',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.RemoveFileRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.RemoveFileResponse.FromString,
                _registered_method=True)
        self.MoveFile = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/MoveFile',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.MoveFileRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.MoveFileResponse.FromString,
                _registered_method=True)
        self.Exec = channel.stream_stream(
                '/tyto.runtime.v1.GuestService/Exec',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ExecRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ExecResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/CreateSession',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/ListSessions',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.KillSession = channel.unary_unary(
                '/tyto.runtime.v1.GuestService/KillSession',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.KillSessionRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.KillSessionResponse.FromString,
                _registered_method=True)
        self.AttachSession = channel.stream_stream(
                '/tyto.runtime.v1.GuestService/AttachSession',
                request_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.AttachSessionRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.AttachSessionResponse.FromString,
                _registered_method=True)


class GuestServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostRestore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareSuspend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortSuspend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FreezeFilesystem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ThawFilesystem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Managed sessions (Sprint 14). Distinct from transient Exec: a session
        outlives the client connection and is identified by name, not by
        stream lifetime. See CreateSessionRequest.name for the identity rule.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KillSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachSession(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.HealthRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.HealthResponse.SerializeToString,
            ),
            'PostRestore': grpc.unary_unary_rpc_method_handler(
                    servicer.PostRestore,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.PostRestoreRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.PostRestoreResponse.SerializeToString,
            ),
            'PrepareSuspend': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareSuspend,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.PrepareSuspendRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.PrepareSuspendResponse.SerializeToString,
            ),
            'AbortSuspend': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortSuspend,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.AbortSuspendRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.AbortSuspendResponse.SerializeToString,
            ),
            'PrepareResume': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareResume,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.PrepareResumeRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.PrepareResumeResponse.SerializeToString,
            ),
            'FreezeFilesystem': grpc.unary_unary_rpc_method_handler(
                    servicer.FreezeFilesystem,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.FreezeFilesystemRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.FreezeFilesystemResponse.SerializeToString,
            ),
            'ThawFilesystem': grpc.unary_unary_rpc_method_handler(
                    servicer.ThawFilesystem,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ThawFilesystemRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ThawFilesystemResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ReadFileRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ReadFileResponse.SerializeToString,
            ),
            'WriteFile': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.WriteFileRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.WriteFileResponse.SerializeToString,
            ),
            'ListDirectory': grpc.unary_stream_rpc_method_handler(
                    servicer.ListDirectory,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ListDirectoryRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ListDirectoryResponse.SerializeToString,
            ),
            'StatFile': grpc.unary_unary_rpc_method_handler(
                    servicer.StatFile,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.StatFileRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.StatFileResponse.SerializeToString,
            ),
            'MakeDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeDirectory,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.MakeDirectoryRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.MakeDirectoryResponse.SerializeToString,
            ),
            'RemoveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFile,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.RemoveFileRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.RemoveFileResponse.SerializeToString,
            ),
            'MoveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveFile,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.MoveFileRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.MoveFileResponse.SerializeToString,
            ),
            'Exec': grpc.stream_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ExecRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ExecResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.CreateSessionRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.CreateSessionResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ListSessionsRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.ListSessionsResponse.SerializeToString,
            ),
            'KillSession': grpc.unary_unary_rpc_method_handler(
                    servicer.KillSession,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.KillSessionRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.KillSessionResponse.SerializeToString,
            ),
            'AttachSession': grpc.stream_stream_rpc_method_handler(
                    servicer.AttachSession,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.AttachSessionRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_guest__pb2.AttachSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tyto.runtime.v1.GuestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tyto.runtime.v1.GuestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GuestService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/Health',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.HealthRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostRestore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/PostRestore',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.PostRestoreRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.PostRestoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareSuspend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/PrepareSuspend',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.PrepareSuspendRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.PrepareSuspendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortSuspend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/AbortSuspend',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.AbortSuspendRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.AbortSuspendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/PrepareResume',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.PrepareResumeRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.PrepareResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FreezeFilesystem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/FreezeFilesystem',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.FreezeFilesystemRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.FreezeFilesystemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ThawFilesystem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/ThawFilesystem',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.ThawFilesystemRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.ThawFilesystemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tyto.runtime.v1.GuestService/ReadFile',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.ReadFileRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/tyto.runtime.v1.GuestService/WriteFile',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.WriteFileRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tyto.runtime.v1.GuestService/ListDirectory',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.ListDirectoryRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.ListDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/StatFile',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.StatFileRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.StatFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/MakeDirectory',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.MakeDirectoryRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.MakeDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/RemoveFile',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.RemoveFileRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.RemoveFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/MoveFile',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.MoveFileRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.MoveFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tyto.runtime.v1.GuestService/Exec',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.ExecRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.ExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/CreateSession',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.CreateSessionRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/ListSessions',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.ListSessionsRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KillSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.GuestService/KillSession',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.KillSessionRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.KillSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AttachSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tyto.runtime.v1.GuestService/AttachSession',
            tyto_dot_runtime_dot_v1_dot_guest__pb2.AttachSessionRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_guest__pb2.AttachSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
