# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import host_pb2 as tyto_dot_runtime_dot_v1_dot_host__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tyto/runtime/v1/host_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HostServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/tyto.runtime.v1.HostService/Create',
                request_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.CreateRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.SuspendSandbox = channel.unary_unary(
                '/tyto.runtime.v1.HostService/SuspendSandbox',
                request_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostSuspendRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostSuspendResponse.FromString,
                _registered_method=True)
        self.ResumeSandbox = channel.unary_unary(
                '/tyto.runtime.v1.HostService/ResumeSandbox',
                request_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostResumeRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostResumeResponse.FromString,
                _registered_method=True)
        self.CreateSnapshot = channel.unary_unary(
                '/tyto.runtime.v1.HostService/CreateSnapshot',
                request_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostCreateSnapshotRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostCreateSnapshotResponse.FromString,
                _registered_method=True)
        self.DeleteSnapshot = channel.unary_unary(
                '/tyto.runtime.v1.HostService/DeleteSnapshot',
                request_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeleteSnapshotRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeleteSnapshotResponse.FromString,
                _registered_method=True)
        self.DeleteSandbox = channel.unary_unary(
                '/tyto.runtime.v1.HostService/DeleteSandbox',
                request_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeleteRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeleteResponse.FromString,
                _registered_method=True)
        self.CreatePreview = channel.unary_unary(
                '/tyto.runtime.v1.HostService/CreatePreview',
                request_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostCreatePreviewRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostCreatePreviewResponse.FromString,
                _registered_method=True)
        self.DeletePreview = channel.unary_unary(
                '/tyto.runtime.v1.HostService/DeletePreview',
                request_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeletePreviewRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeletePreviewResponse.FromString,
                _registered_method=True)
        self.ListPreviews = channel.unary_unary(
                '/tyto.runtime.v1.HostService/ListPreviews',
                request_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostListPreviewsRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostListPreviewsResponse.FromString,
                _registered_method=True)


class HostServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuspendSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePreview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePreview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPreviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.CreateRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.CreateResponse.SerializeToString,
            ),
            'SuspendSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.SuspendSandbox,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostSuspendRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostSuspendResponse.SerializeToString,
            ),
            'ResumeSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeSandbox,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostResumeRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostResumeResponse.SerializeToString,
            ),
            'CreateSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSnapshot,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostCreateSnapshotRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostCreateSnapshotResponse.SerializeToString,
            ),
            'DeleteSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSnapshot,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeleteSnapshotRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeleteSnapshotResponse.SerializeToString,
            ),
            'DeleteSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSandbox,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeleteRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeleteResponse.SerializeToString,
            ),
            'CreatePreview': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePreview,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostCreatePreviewRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostCreatePreviewResponse.SerializeToString,
            ),
            'DeletePreview': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePreview,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeletePreviewRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeletePreviewResponse.SerializeToString,
            ),
            'ListPreviews': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPreviews,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostListPreviewsRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_host__pb2.HostListPreviewsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tyto.runtime.v1.HostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tyto.runtime.v1.HostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HostService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.HostService/Create',
            tyto_dot_runtime_dot_v1_dot_host__pb2.CreateRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_host__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuspendSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.HostService/SuspendSandbox',
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostSuspendRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostSuspendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.HostService/ResumeSandbox',
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostResumeRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.HostService/CreateSnapshot',
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostCreateSnapshotRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostCreateSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.HostService/DeleteSnapshot',
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeleteSnapshotRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeleteSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.HostService/DeleteSandbox',
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeleteRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.HostService/CreatePreview',
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostCreatePreviewRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostCreatePreviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.HostService/DeletePreview',
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeletePreviewRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostDeletePreviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPreviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.HostService/ListPreviews',
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostListPreviewsRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_host__pb2.HostListPreviewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
