# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tyto/runtime/v1/preview.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tyto/runtime/v1/preview.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dtyto/runtime/v1/preview.proto\x12\x0ftyto.runtime.v1\"\xa7\x01\n\rPreviewRecord\x12\x12\n\npreview_id\x18\x01 \x01(\t\x12\x12\n\nsandbox_id\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x33\n\tauth_mode\x18\x04 \x01(\x0e\x32 .tyto.runtime.v1.PreviewAuthMode\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x1d\n\x15\x63reated_at_unix_nanos\x18\x06 \x01(\x03*o\n\x0fPreviewAuthMode\x12!\n\x1dPREVIEW_AUTH_MODE_UNSPECIFIED\x10\x00\x12\x1b\n\x17PREVIEW_AUTH_MODE_TOKEN\x10\x01\x12\x1c\n\x18PREVIEW_AUTH_MODE_PUBLIC\x10\x02\x42<Z:github.com/bonyai/compute/gen/go/tyto/runtime/v1;runtimev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tyto._proto.tyto.runtime.v1.preview_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/bonyai/compute/gen/go/tyto/runtime/v1;runtimev1'
  _globals['_PREVIEWAUTHMODE']._serialized_start=220
  _globals['_PREVIEWAUTHMODE']._serialized_end=331
  _globals['_PREVIEWRECORD']._serialized_start=51
  _globals['_PREVIEWRECORD']._serialized_end=218
# @@protoc_insertion_point(module_scope)
