# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tapi_pb2 as tyto_dot_runtime_dot_v1_dot_tapi__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tyto/runtime/v1/tapi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TApiServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/tyto.runtime.v1.TApiService/Create',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiServiceCreateRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiServiceCreateResponse.FromString,
                _registered_method=True)
        self.GetSandbox = channel.unary_unary(
                '/tyto.runtime.v1.TApiService/GetSandbox',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiGetSandboxRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiGetSandboxResponse.FromString,
                _registered_method=True)
        self.ListSandboxes = channel.unary_unary(
                '/tyto.runtime.v1.TApiService/ListSandboxes',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListSandboxesRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListSandboxesResponse.FromString,
                _registered_method=True)
        self.ResumeSandbox = channel.unary_unary(
                '/tyto.runtime.v1.TApiService/ResumeSandbox',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiResumeSandboxRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiResumeSandboxResponse.FromString,
                _registered_method=True)
        self.CreateSnapshot = channel.unary_unary(
                '/tyto.runtime.v1.TApiService/CreateSnapshot',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiCreateSnapshotRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiCreateSnapshotResponse.FromString,
                _registered_method=True)
        self.DeleteSnapshot = channel.unary_unary(
                '/tyto.runtime.v1.TApiService/DeleteSnapshot',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeleteSnapshotRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeleteSnapshotResponse.FromString,
                _registered_method=True)
        self.DeleteSandbox = channel.unary_unary(
                '/tyto.runtime.v1.TApiService/DeleteSandbox',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeleteSandboxRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeleteSandboxResponse.FromString,
                _registered_method=True)
        self.ReissueCapability = channel.unary_unary(
                '/tyto.runtime.v1.TApiService/ReissueCapability',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiReissueCapabilityRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiReissueCapabilityResponse.FromString,
                _registered_method=True)
        self.CreatePreview = channel.unary_unary(
                '/tyto.runtime.v1.TApiService/CreatePreview',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiCreatePreviewRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiCreatePreviewResponse.FromString,
                _registered_method=True)
        self.DeletePreview = channel.unary_unary(
                '/tyto.runtime.v1.TApiService/DeletePreview',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeletePreviewRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeletePreviewResponse.FromString,
                _registered_method=True)
        self.ListPreviews = channel.unary_unary(
                '/tyto.runtime.v1.TApiService/ListPreviews',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListPreviewsRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListPreviewsResponse.FromString,
                _registered_method=True)
        self.ListOrganizations = channel.unary_unary(
                '/tyto.runtime.v1.TApiService/ListOrganizations',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListOrganizationsRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListOrganizationsResponse.FromString,
                _registered_method=True)


class TApiServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSandboxes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReissueCapability(self, request, context):
        """ReissueCapability mints a fresh exec-capability JWS for a sandbox whose
        Create-issued token has expired (Sprint 14, plan D10/S14.7). Same
        minting path as Create; binds the current authority generation from
        the control-plane projection. Existing unexpired tokens remain valid;
        this does not revoke them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePreview(self, request, context):
        """Preview URLs (Sprint 15). TApi mints the preview id and owns the public
        URL; Nestled records and publishes the binding and never sees a domain.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePreview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPreviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrganizations(self, request, context):
        """ListOrganizations reports the organizations the calling api_key's user
        belongs to. Read-only: organization creation, renaming, membership, and
        invitations stay on the JWT-authenticated REST surface, because an api key
        is a user credential and those are account-management operations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TApiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiServiceCreateRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiServiceCreateResponse.SerializeToString,
            ),
            'GetSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSandbox,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiGetSandboxRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiGetSandboxResponse.SerializeToString,
            ),
            'ListSandboxes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSandboxes,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListSandboxesRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListSandboxesResponse.SerializeToString,
            ),
            'ResumeSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeSandbox,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiResumeSandboxRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiResumeSandboxResponse.SerializeToString,
            ),
            'CreateSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSnapshot,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiCreateSnapshotRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiCreateSnapshotResponse.SerializeToString,
            ),
            'DeleteSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSnapshot,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeleteSnapshotRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeleteSnapshotResponse.SerializeToString,
            ),
            'DeleteSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSandbox,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeleteSandboxRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeleteSandboxResponse.SerializeToString,
            ),
            'ReissueCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.ReissueCapability,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiReissueCapabilityRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiReissueCapabilityResponse.SerializeToString,
            ),
            'CreatePreview': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePreview,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiCreatePreviewRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiCreatePreviewResponse.SerializeToString,
            ),
            'DeletePreview': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePreview,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeletePreviewRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeletePreviewResponse.SerializeToString,
            ),
            'ListPreviews': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPreviews,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListPreviewsRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListPreviewsResponse.SerializeToString,
            ),
            'ListOrganizations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOrganizations,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListOrganizationsRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListOrganizationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tyto.runtime.v1.TApiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tyto.runtime.v1.TApiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TApiService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiService/Create',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiServiceCreateRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiServiceCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiService/GetSandbox',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiGetSandboxRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiGetSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSandboxes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiService/ListSandboxes',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListSandboxesRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListSandboxesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiService/ResumeSandbox',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiResumeSandboxRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiResumeSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiService/CreateSnapshot',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiCreateSnapshotRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiCreateSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiService/DeleteSnapshot',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeleteSnapshotRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeleteSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiService/DeleteSandbox',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeleteSandboxRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeleteSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReissueCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiService/ReissueCapability',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiReissueCapabilityRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiReissueCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiService/CreatePreview',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiCreatePreviewRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiCreatePreviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiService/DeletePreview',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeletePreviewRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiDeletePreviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPreviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiService/ListPreviews',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListPreviewsRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListPreviewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOrganizations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiService/ListOrganizations',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListOrganizationsRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.TApiListOrganizationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TApiHostReportServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportObservedState = channel.unary_unary(
                '/tyto.runtime.v1.TApiHostReportService/ReportObservedState',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.ReportObservedStateRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.ReportObservedStateResponse.FromString,
                _registered_method=True)
        self.ReportTerminal = channel.unary_unary(
                '/tyto.runtime.v1.TApiHostReportService/ReportTerminal',
                request_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.ReportTerminalRequest.SerializeToString,
                response_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.ReportTerminalResponse.FromString,
                _registered_method=True)


class TApiHostReportServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ReportObservedState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTerminal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TApiHostReportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportObservedState': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportObservedState,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.ReportObservedStateRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.ReportObservedStateResponse.SerializeToString,
            ),
            'ReportTerminal': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTerminal,
                    request_deserializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.ReportTerminalRequest.FromString,
                    response_serializer=tyto_dot_runtime_dot_v1_dot_tapi__pb2.ReportTerminalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tyto.runtime.v1.TApiHostReportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tyto.runtime.v1.TApiHostReportService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TApiHostReportService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportObservedState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiHostReportService/ReportObservedState',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.ReportObservedStateRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.ReportObservedStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTerminal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tyto.runtime.v1.TApiHostReportService/ReportTerminal',
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.ReportTerminalRequest.SerializeToString,
            tyto_dot_runtime_dot_v1_dot_tapi__pb2.ReportTerminalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
